version: '3.8'

services:
  application:
    build:
      context: .
      args:
        APP_ENV: dev
    container_name: recru-app
    volumes:
      - ./:/var/www/html:cached
    depends_on:
      - db
    networks:
      app-net:
        ipv4_address: 172.87.0.2

  nginx:
    image: nginx:latest
    ports:
      - 8888:80
    links:
      -  application
    volumes:
      - ./:/var/www/html:delegated
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      app-net: ~

  db:
    image: postgres:12.5-alpine
    container_name: recru-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-vol:/docker-entrypoint-initdb.d:cached
    networks:
      app-net:
        ipv4_address: 172.87.0.3

networks:
  app-net:
    ipam:
      config:
        - subnet: 172.87.0.0/16

volumes:
  postgres-vol: ~
